# Generated by Django 5.1.5 on 2025-01-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of purchase')),
                ('vendor', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=200)),
                ('purchase_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='purchase total')),
                ('snap', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='SNAP')),
                ('wicsenior', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='WIC/Senior')),
                ('match_snap', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='SNAP matching')),
                ('match_wicsenior', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='WIC/Senior matching')),
                ('cash_credit', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='cash/credit')),
            ],
        ),
    ]
