# Generated by Django 5.1.5 on 2025-01-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactionlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cash_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='cash/credit'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='match_snap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='SNAP matching'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='match_wicsenior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='WIC/Senior matching'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='snap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='SNAP'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wicsenior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='WIC/Senior'),
        ),
    ]
